version: '3.4'
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-new
    ports:
      - "6379:6379"
    volumes:
      - ./reddit/src/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf","--requirepass bodazopa2020"]