
import  "@/app/globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/navbar/Navbar"
import { getStateFromCookiesStorage } from "@/utils/getUserState";



export default async function RootLayout({ children }:any) {
  const userState = await getStateFromCookiesStorage();
  return (
      <html lang="en" className="min-h-[100vw]">
        <body className="min-h-[100vw] overflow-x-hidden overflow-y-scroll bg-[#242424] relative">
          <Navbar user={userState}/>
          {children}
        </body>
      </html>
  );
}
