
import  "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/navbar/Navbar"
import { getStateFromCookiesStorage } from "@/utils/getUserState";



export default async function RootLayout({ children }:any) {
  const userState = await getStateFromCookiesStorage();
  return (
      <html lang="en">
        <body>
          <Navbar user={userState}/>
          {children}
        </body>
      </html>
  );
}
