import { Providers } from "@/components/redux/provider";
import  "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/navbar/Navbar"
import { getStateFromRedisStorage } from "@/utils/getUserState";



export default async function RootLayout({ children }:any) {
  const userState = await getStateFromRedisStorage();
  return (
    <Providers>
      <html lang="en">
        <body>
          <Navbar user={userState}/>
          {children}
        </body>
      </html>
    </Providers>
  );
}
